version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    assignees:
      - jamesjarvis
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - jamesjarvis
